[package]
name = "grephite"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.2"
bevy_egui = { version = "0.38.0", features = ["immutable_ctx"] }
bevy_pancam = "0.19"
rand="0.9.2"
mlua={version="0.11.4", features = ["lua54", "vendored", "send"]}